{% set version = '1.1.3' %}
{% set buildnum = '4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mapi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapi/mapi_{{ version }}.tar.gz
  sha256: 6433cd4628974e00649893abf82b7a8c86aae8dbd6ea76a17af5f1e64dd543e0

build:
  number: {{ buildnum }}
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-rcpp                           # [build_platform != target_platform]
  host:
    - r-base
    - r-lang
    - r-rcpp
    - r-data.table
    - r-s2
    - r-sf
    - r-fmesher
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-latticeextra
    - r-sp
    - r-progress
    - r-dggridr
    - r-testthat
  run:
    - r-base
    - r-rcpp
    - r-data.table
    - r-s2
    - r-sf
    - r-fmesher
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-latticeextra
    - r-sp
    - r-progress
    - r-dggridr
    - r-testthat

test:
  commands:
    - $R -e "library('mapi')"           # [not win]
    - "\"%R%\" -e \"library('mapi')\""  # [win]

about:
  home: https://www1.montpellier.inra.fr/CBGP/software/MAPI/
  license: GPL-3.0-or-later
  summary: Mapping Averaged Pairwise Information (MAPI) is an exploratory method providing graphical
    representations summarizing the spatial variation of pairwise metrics (eg. distance,
    similarity coefficient, ...) computed between georeferenced samples.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - spiry34

# Package: mapi
# Type: Package
# Title: Mapping Averaged Pairwise Information
# Version: 1.1.3
# Authors: Sylvain Piry and the authors of mapi package
# Description: Mapping Averaged Pairwise Information (MAPI) is an exploratory method providing graphical representations summarizing the spatial variation of pairwise metrics (eg. distance, similarity coefficient, ...) computed between georeferenced samples.
# License: GPL (>= 3)
# URL: https://www1.montpellier.inrae.fr/CBGP/software/MAPI/
# Repository: CRAN
# Depends: R (>= 4.1)
# LinkingTo: Rcpp
# Imports: data.table, doParallel, fmesher, foreach, Rcpp, s2, sf
# Suggests: dggridR, ggplot2, latticeExtra, progress, sp, testthat (>= 3.0.0)
