{% set version = '1.1.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mapi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapi/mapi_{{ version }}.tar.gz
  sha256: 7c69f9736bce73c8420fa4a23fe543159674b12ab66abcb48883acf9afda92fa

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.1
    - r-rcpp
    - r-data.table
    - r-s2
    - r-sf
    - r-fmesher
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-latticeextra
    - r-sp
    - r-progress
    - r-dggridr
    - r-testthat
  run:
    - r-base >=4.1
    - r-rcpp
    - r-data.table
    - r-s2
    - r-sf
    - r-fmesher
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-latticeextra
    - r-sp
    - r-progress
    - r-dggridr
    - r-testthat

test:
  commands:
    - $R -e "library('mapi')"           # [not win]
    - "\"%R%\" -e \"library('mapi')\""  # [win]

about:
  home: https://www1.montpellier.inra.fr/CBGP/software/MAPI/
  license: GPL-3.0-or-later
  summary: Mapping Averaged Pairwise Information (MAPI) is an exploratory method providing graphical
    representations summarizing the spatial variation of pairwise metrics (eg. distance,
    similarity coefficient, ...) computed between georeferenced samples.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - spiry34

#Package: mapi
#Title: Mapping Averaged Pairwise Information
#Version: 1.1.3
#Authors@R: c(
    #person("Sylvain", "Piry", , "sylvain.piry@inrae.fr", role = c("aut", "cre"),
           #comment = c(ORCID = "0000-0002-7717-7555")),
    #person("Thomas", "Campolunghi", role = "aut"),
    #person("Florent", "Cestier", role = "aut"),
    #person("Karine", "Berthier", , "karine.berthier@inrae.fr", role = "aut",
           #comment = c(ORCID = "0000-0002-2260-7968"))
  #)
#Description: Mapping Averaged Pairwise Information (MAPI) is an
    #exploratory method providing graphical representations summarizing the
    #spatial variation of pairwise metrics (eg. distance, similarity
    #coefficient, ...) computed between georeferenced samples.
#License: GPL (>= 3)
#URL: https://www1.montpellier.inrae.fr/CBGP/software/MAPI/
#Encoding: UTF-8
#Language: en-US
#Roxygen: list(markdown = TRUE)
#RoxygenNote: 7.3.2
#Depends: 
    #R (>= 4.1)
#LinkingTo: 
    #Rcpp
#Imports: 
    #data.table,
    #doParallel,
    #fmesher,
    #foreach,
    #Rcpp,
    #s2,
    #sf
#Suggests: 
    #dggridR,
    #ggplot2,
    #latticeExtra,
    #progress,
    #sp,
    #testthat (>= 3.0.0)
#Config/testthat/edition: 3
#LazyData: true
